<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Dashboard extends CI_Controller{
    function __construct()
    {
        parent::__construct();

    }

    function index()
    {




        if (!$this->ion_auth->logged_in()) {
            // redirect them to the login page
            redirect('auth/login', 'refresh');
        } else {


            $data['_view'] = 'dashboard';
            $this->load->view('layouts/main',$data);
        }





    }
}
