<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Document extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Document_model');
    }

    /*
     * Listing of documents
     */
    function index()
    {
        if (!$this->ion_auth->is_admin()) {
            // redirect them to the login page
            redirect('auth/login', 'refresh');
        } else {

            $data['documents'] = $this->Document_model->get_all_documents();
            $data['_view'] = 'document/index';
            $this->load->view('layouts/main', $data);
        }
    }

    function get_documents($id)
    {
        if (!$this->ion_auth->logged_in()) {
            // redirect them to the login page
            redirect('auth/login', 'refresh');
        } else {
            $data['documents'] = $this->Document_model->get_documents($id);
            $this->load->model('Report_model');
            $data['report'] = $this->Report_model->get_report($id);
            $data['_view'] = 'document/documents';
            $this->load->view('layouts/main', $data);
        }
    }

    /*
     * Adding a new document
     */
    function add()
    {
        if (!$this->ion_auth->is_admin()) {
            // redirect them to the login page
            redirect('auth/login', 'refresh');
        } else {

            if (isset($_POST) && count($_POST) > 0) {
                $params = array(
                    'report_id' => $this->input->post('report_id'),
                    'name' => $this->input->post('name'),
                    'data' => $this->input->post('data'),
                );

                $document_id = $this->Document_model->add_document($params);
                redirect('document/index');
            } else {
                $this->load->model('Report_model');
                $data['all_report'] = $this->Report_model->get_all_report();

                $data['_view'] = 'document/add';
                $this->load->view('layouts/main', $data);
            }
        }
    }

    /*
     * Editing a document
     */
    function edit($id)
    {
        if (!$this->ion_auth->is_admin()) {
            // redirect them to the login page
            redirect('auth/login', 'refresh');
        } else {

            // check if the document exists before trying to edit it
            $data['document'] = $this->Document_model->get_document($id);

            if (isset($data['document']['id'])) {
                if (isset($_POST) && count($_POST) > 0) {
                    $params = array(
                        'report_id' => $this->input->post('report_id'),
                        'name' => $this->input->post('name'),
                        'data' => $this->input->post('data'),
                    );

                    $this->Document_model->update_document($id, $params);
                    redirect('document/index');
                } else {
                    $this->load->model('Report_model');
                    $data['all_report'] = $this->Report_model->get_all_report();

                    $data['_view'] = 'document/edit';
                    $this->load->view('layouts/main', $data);
                }
            } else {
                show_error('The document you are trying to edit does not exist.');
            }
        }
    }

    /*
     * Deleting document
     */
    function remove($id)
    {
        if (!$this->ion_auth->is_admin()) {
            // redirect them to the login page
            redirect('auth/login', 'refresh');
        } else {

            $document = $this->Document_model->get_document($id);

            // check if the document exists before trying to delete it
            if (isset($document['id'])) {
                $this->Document_model->delete_document($id);
                redirect('document/index');
            } else {
                show_error('The document you are trying to delete does not exist.');
            }
        }
    }

}
