<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Employer extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Employer_model');
    }

    /*
     * Listing of employer
     */
    function index()
    {
        if (!$this->ion_auth->is_admin()) {
            // redirect them to the login page
            redirect('/', 'refresh');
        } else {

            $data['employer'] = $this->Employer_model->get_all_employer();

            $data['_view'] = 'employer/index';
            $this->load->view('layouts/main', $data);
        }
    }

    /*
     * Adding a new employer
     */
    function add()
    {
        if (!$this->ion_auth->is_admin()) {
            // redirect them to the login page
            redirect('/', 'refresh');
        } else {

            if (isset($_POST) && count($_POST) > 0) {
                $params = array(
                    'user_id' => $this->input->post('user_id'),
                );

                $employer_id = $this->Employer_model->add_employer($params);
                redirect('employer/index');
            } else {
                $data['_view'] = 'employer/add';
                $this->load->view('layouts/main', $data);
            }
        }
    }

    /*
     * Editing a employer
     */
    function edit($id)
    {
        if (!$this->ion_auth->is_admin()) {
            // redirect them to the login page
            redirect('/', 'refresh');
        } else {

            // check if the employer exists before trying to edit it
            $data['employer'] = $this->Employer_model->get_employer($id);

            if (isset($data['employer']['id'])) {
                if (isset($_POST) && count($_POST) > 0) {
                    $params = array(
                        'user_id' => $this->input->post('user_id'),
                    );

                    $this->Employer_model->update_employer($id, $params);
                    redirect('employer/index');
                } else {
                    $data['_view'] = 'employer/edit';
                    $this->load->view('layouts/main', $data);
                }
            } else {
                show_error('The employer you are trying to edit does not exist.');
            }
        }
    }

    /*
     * Deleting employer
     */
    function remove($id)
    {
        if (!$this->ion_auth->is_admin()) {
            // redirect them to the login page
            redirect('/', 'refresh');
        } else {

            $employer = $this->Employer_model->get_employer($id);

            // check if the employer exists before trying to delete it
            if (isset($employer['id'])) {
                $this->Employer_model->delete_employer($id);
                redirect('employer/index');
            } else {
                show_error('The employer you are trying to delete does not exist.');
            }
        }
    }

}
