<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Material extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Material_model');
    } 

    /*
     * Listing of materials
     */
    function index()
    {
        $data['materials'] = $this->Material_model->get_all_materials();
        
        $data['_view'] = 'material/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new material
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'project_id' => $this->input->post('project_id'),
				'name' => $this->input->post('name'),
				'unit' => $this->input->post('unit'),
				'quantity' => $this->input->post('quantity'),
            );
            
            $material_id = $this->Material_model->add_material($params);
            redirect('material/index');
        }
        else
        {
			$this->load->model('Project_model');
			$data['all_project'] = $this->Project_model->get_all_project();
            
            $data['_view'] = 'material/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a material
     */
    function edit($id)
    {   
        // check if the material exists before trying to edit it
        $data['material'] = $this->Material_model->get_material($id);
        
        if(isset($data['material']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'project_id' => $this->input->post('project_id'),
					'name' => $this->input->post('name'),
					'unit' => $this->input->post('unit'),
					'quantity' => $this->input->post('quantity'),
                );

                $this->Material_model->update_material($id,$params);            
                redirect('material/index');
            }
            else
            {
				$this->load->model('Project_model');
				$data['all_project'] = $this->Project_model->get_all_project();

                $data['_view'] = 'material/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The material you are trying to edit does not exist.');
    } 

    /*
     * Deleting material
     */
    function remove($id)
    {
        $material = $this->Material_model->get_material($id);

        // check if the material exists before trying to delete it
        if(isset($material['id']))
        {
            $this->Material_model->delete_material($id);
            redirect('material/index');
        }
        else
            show_error('The material you are trying to delete does not exist.');
    }
    
}
