<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Report extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Report_model');
    }

    /*
     * Listing of report
     */
    function index()
    {
        if (!$this->ion_auth->is_admin()) {
            // redirect them to the login page
            redirect('/', 'refresh');
        } else {
            $data['report'] = $this->Report_model->get_all_report();

            $data['_view'] = 'report/index';
            $this->load->view('layouts/main', $data);
        }
    }

    /*
     * Adding a new report
     */
    function add()
    {
        if (!$this->ion_auth->is_admin()) {
            // redirect them to the login page
            redirect('/', 'refresh');
        } else {

            if (isset($_POST) && count($_POST) > 0) {
                $params = array(
                    'task_id' => $this->input->post('task_id'),
                    'workman_id' => $this->input->post('workman_id'),
                    'amount' => $this->input->post('amount'),
                    'type_of_work' => $this->input->post('type_of_work'),
                    'work_hours' => $this->input->post('work_hours'),
                    'sendtime' => date("Y-m-d H:i:s"),
                );

                $report_id = $this->Report_model->add_report($params);
                redirect('report/index');
            } else {
                $this->load->model('Task_model');
                $data['all_task'] = $this->Task_model->get_all_task();

                $this->load->model('Workman_model');
                $data['all_workman'] = $this->Workman_model->get_all_workman();

                $data['_view'] = 'report/add';
                $this->load->view('layouts/main', $data);
            }
        }
    }

    /*
     * Editing a report
     */
    function edit($id)
    {
        if (!$this->ion_auth->logged_in()) {
            // redirect them to the login page
            redirect('/', 'refresh');
        } else {

            // check if the report exists before trying to edit it
            $data['report'] = $this->Report_model->get_report($id);

            if (isset($data['report']['id'])) {
                if (isset($_POST) && count($_POST) > 0) {
                    $params = array(
                        'task_id' => $this->input->post('task_id'),
                        'workman_id' => $this->input->post('workman_id'),
                        'amount' => $this->input->post('amount'),
                        'type_of_work' => $this->input->post('type_of_work'),
                        'work_hours' => $this->input->post('work_hours'),
                        'sendtime' => date("Y-m-d H:i:s"),
                        'status_id' => $this->input->post('status_id'),
                    );

                    $this->Report_model->update_report($id, $params);
                    redirect('report/index');
                } else {
                    $this->load->model('Task_model');
                    $data['all_task'] = $this->Task_model->get_all_task();

                    $this->load->model('Status_model');
                    $data['all_status'] = $this->Status_model->get_all_status();


                    $this->load->model('Workman_model');
                    $data['all_workman'] = $this->Workman_model->get_all_workman();

                    $data['_view'] = 'report/edit';
                    $this->load->view('layouts/main', $data);
                }
            } else {
                show_error('The report you are trying to edit does not exist.');
            }
        }
    }

    /*
   * Editing a report
   */
    function edit_by_user($id)
    {
        if (!$this->ion_auth->logged_in()) {
            // redirect them to the login page
            redirect('/', 'refresh');
        } else {

            // check if the report exists before trying to edit it
            $data['report'] = $this->Report_model->get_report($id);

            if (isset($data['report']['id'])) {
                if (isset($_POST) && count($_POST) > 0) {
                    $params = array(
                        'status_id' => $this->input->post('status_id'),
                    );

                    $this->Report_model->update_report($id, $params);
                    redirect('task/get_detail/' . $data['report']['task_id']);
                } else {
                    $this->load->model('Task_model');
                    $data['all_task'] = $this->Task_model->get_all_task();

                    $this->load->model('Status_model');
                    $data['all_status'] = $this->Status_model->get_all_status();


                    $this->load->model('Workman_model');
                    $data['all_workman'] = $this->Workman_model->get_all_workman();

                    $data['_view'] = 'report/edit';
                    $this->load->view('layouts/main', $data);
                }
            } else {
                show_error('The report you are trying to edit does not exist.');
            }
        }
    }

    /*
     * Deleting report
     */
    function remove($id)
    {
        if (!$this->ion_auth->is_admin()) {
            // redirect them to the login page
            redirect('/', 'refresh');
        } else {

            $report = $this->Report_model->get_report($id);

            // check if the report exists before trying to delete it
            if (isset($report['id'])) {
                $this->Report_model->delete_report($id);
                redirect('report/index');
            } else {
                show_error('The report you are trying to delete does not exist.');
            }
        }
    }
}
