<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Report extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Report_model');
    } 

    /*
     * Listing of report
     */
    function index()
    {
        $data['report'] = $this->Report_model->get_all_report();
        
        $data['_view'] = 'report/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new report
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'task_id' => $this->input->post('task_id'),
				'workman_id' => $this->input->post('workman_id'),
				'amount' => $this->input->post('amount'),
				'type_of_work' => $this->input->post('type_of_work'),
				'work_hours' => $this->input->post('work_hours'),
				'sendtime' => $this->input->post('sendtime'),
            );
            
            $report_id = $this->Report_model->add_report($params);
            redirect('report/index');
        }
        else
        {
			$this->load->model('Task_model');
			$data['all_task'] = $this->Task_model->get_all_task();

			$this->load->model('Workman_model');
			$data['all_workman'] = $this->Workman_model->get_all_workman();
            
            $data['_view'] = 'report/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a report
     */
    function edit($id)
    {   
        // check if the report exists before trying to edit it
        $data['report'] = $this->Report_model->get_report($id);
        
        if(isset($data['report']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'task_id' => $this->input->post('task_id'),
					'workman_id' => $this->input->post('workman_id'),
					'amount' => $this->input->post('amount'),
					'type_of_work' => $this->input->post('type_of_work'),
					'work_hours' => $this->input->post('work_hours'),
					'sendtime' => $this->input->post('sendtime'),
                );

                $this->Report_model->update_report($id,$params);            
                redirect('report/index');
            }
            else
            {
				$this->load->model('Task_model');
				$data['all_task'] = $this->Task_model->get_all_task();

				$this->load->model('Workman_model');
				$data['all_workman'] = $this->Workman_model->get_all_workman();

                $data['_view'] = 'report/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The report you are trying to edit does not exist.');
    } 

    /*
     * Deleting report
     */
    function remove($id)
    {
        $report = $this->Report_model->get_report($id);

        // check if the report exists before trying to delete it
        if(isset($report['id']))
        {
            $this->Report_model->delete_report($id);
            redirect('report/index');
        }
        else
            show_error('The report you are trying to delete does not exist.');
    }
    
}
