<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Statu extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Statu_model');
    } 

    /*
     * Listing of status
     */
    function index()
    {
        $data['status'] = $this->Statu_model->get_all_status();
        
        $data['_view'] = 'statu/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new statu
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'name' => $this->input->post('name'),
            );
            
            $statu_id = $this->Statu_model->add_statu($params);
            redirect('statu/index');
        }
        else
        {            
            $data['_view'] = 'statu/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a statu
     */
    function edit($id)
    {   
        // check if the statu exists before trying to edit it
        $data['statu'] = $this->Statu_model->get_statu($id);
        
        if(isset($data['statu']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'name' => $this->input->post('name'),
                );

                $this->Statu_model->update_statu($id,$params);            
                redirect('statu/index');
            }
            else
            {
                $data['_view'] = 'statu/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The statu you are trying to edit does not exist.');
    } 

    /*
     * Deleting statu
     */
    function remove($id)
    {
        $statu = $this->Statu_model->get_statu($id);

        // check if the statu exists before trying to delete it
        if(isset($statu['id']))
        {
            $this->Statu_model->delete_statu($id);
            redirect('statu/index');
        }
        else
            show_error('The statu you are trying to delete does not exist.');
    }
    
}
