<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Task extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Task_model');
    } 

    /*
     * Listing of task
     */
    function index()
    {
        $data['task'] = $this->Task_model->get_all_task();
        
        $data['_view'] = 'task/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new task
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'project_id' => $this->input->post('project_id'),
				'status_id' => $this->input->post('status_id'),
				'quantity' => $this->input->post('quantity'),
				'unit' => $this->input->post('unit'),
				'name' => $this->input->post('name'),
				'description' => $this->input->post('description'),
				'deadline' => $this->input->post('deadline'),
            );
            
            $task_id = $this->Task_model->add_task($params);
            redirect('task/index');
        }
        else
        {
			$this->load->model('Project_model');
			$data['all_project'] = $this->Project_model->get_all_project();

			$this->load->model('Statu_model');
			$data['all_status'] = $this->Statu_model->get_all_status();
            
            $data['_view'] = 'task/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a task
     */
    function edit($id)
    {   
        // check if the task exists before trying to edit it
        $data['task'] = $this->Task_model->get_task($id);
        
        if(isset($data['task']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'project_id' => $this->input->post('project_id'),
					'status_id' => $this->input->post('status_id'),
					'quantity' => $this->input->post('quantity'),
					'unit' => $this->input->post('unit'),
					'name' => $this->input->post('name'),
					'description' => $this->input->post('description'),
					'deadline' => $this->input->post('deadline'),
                );

                $this->Task_model->update_task($id,$params);            
                redirect('task/index');
            }
            else
            {
				$this->load->model('Project_model');
				$data['all_project'] = $this->Project_model->get_all_project();

				$this->load->model('Statu_model');
				$data['all_status'] = $this->Statu_model->get_all_status();

                $data['_view'] = 'task/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The task you are trying to edit does not exist.');
    } 

    /*
     * Deleting task
     */
    function remove($id)
    {
        $task = $this->Task_model->get_task($id);

        // check if the task exists before trying to delete it
        if(isset($task['id']))
        {
            $this->Task_model->delete_task($id);
            redirect('task/index');
        }
        else
            show_error('The task you are trying to delete does not exist.');
    }
    
}
