<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Employer_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get employer by id
     */
    function get_employer($id)
    {
        return $this->db->get_where('employer',array('id'=>$id))->row_array();
    }

    function get_employer_by_user($user_id)
    {
        $this->db->where('user_id',$user_id);
        return $this->db->get('employer')->result_array();
    }
        
    /*
     * Get all employer
     */
    function get_all_employer()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('employer')->result_array();
    }
        
    /*
     * function to add new employer
     */
    function add_employer($params)
    {
        $this->db->insert('employer',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update employer
     */
    function update_employer($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('employer',$params);
    }
    
    /*
     * function to delete employer
     */
    function delete_employer($id)
    {
        return $this->db->delete('employer',array('id'=>$id));
    }
}
