<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Manager_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get manager by id
     */
    function get_manager($id)
    {
        return $this->db->get_where('manager',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all manager
     */
    function get_all_manager()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('manager')->result_array();
    }
        
    /*
     * function to add new manager
     */
    function add_manager($params)
    {
        $this->db->insert('manager',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update manager
     */
    function update_manager($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('manager',$params);
    }
    
    /*
     * function to delete manager
     */
    function delete_manager($id)
    {
        return $this->db->delete('manager',array('id'=>$id));
    }
}
