<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Material_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get material by id
     */
    function get_material($id)
    {
        return $this->db->get_where('materials',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all materials
     */
    function get_all_materials()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('materials')->result_array();
    }

    function get_tasks_materials($task_id)
    {
        $this->db->where('task_id',$task_id);
        return $this->db->get('materials')->result_array();
    }

    /*
     * function to add new material
     */
    function add_material($params)
    {
        $this->db->insert('materials',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update material
     */
    function update_material($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('materials',$params);
    }
    
    /*
     * function to delete material
     */
    function delete_material($id)
    {
        return $this->db->delete('materials',array('id'=>$id));
    }
}
