<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Report_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get report by id
     */
    function get_report($id)
    {
        return $this->db->get_where('report', array('id' => $id))->row_array();
    }

    /*
     * Get all report
     */
    function get_all_report()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('report')->result_array();
    }

    /*
     * function to add new report
     */
    function add_report($params)
    {
        $this->db->insert('report', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update report
     */
    function update_report($id, $params)
    {
        $this->db->where('id', $id);
        return $this->db->update('report', $params);
    }

    function get_task_reports($task_id)
    {
        $this->db->where('task_id', $task_id);
        return $this->db->get('report')->result_array();
    }

    /*
     * function to delete report
     */
    function delete_report($id)
    {
        return $this->db->delete('report', array('id' => $id));
    }
}
