<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Task_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get task by id
     */
    function get_task($id)
    {
        return $this->db->get_where('Task',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all task
     */
    function get_all_task()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('Task')->result_array();
    }
        
    /*
     * function to add new task
     */
    function add_task($params)
    {
        $this->db->insert('Task',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update task
     */
    function update_task($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('Task',$params);
    }
    
    /*
     * function to delete task
     */
    function delete_task($id)
    {
        return $this->db->delete('Task',array('id'=>$id));
    }
}
