<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Wasted_material_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get wasted_material by id
     */
    function get_wasted_material($id)
    {
        return $this->db->get_where('wasted_materials',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all wasted_materials
     */
    function get_all_wasted_materials()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('wasted_materials')->result_array();
    }

    function get_reports_wMaterials($report_id)
    {
        $this->db->where('report_id', $report_id);
        return $this->db->get('wasted_materials')->result_array();
    }
        
    /*
     * function to add new wasted_material
     */
    function add_wasted_material($params)
    {
        $this->db->insert('wasted_materials',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update wasted_material
     */
    function update_wasted_material($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('wasted_materials',$params);
    }
    
    /*
     * function to delete wasted_material
     */
    function delete_wasted_material($id)
    {
        return $this->db->delete('wasted_materials',array('id'=>$id));
    }
}
